#!/usr/bin/env bash

#SBATCH --job-name=test
#SBATCH --partition=dept.physics
#SBATCH --nodes=4
#SBATCH --ntasks-per-node=56
#SBATCH --time=100:00:00
#SBATCH --mem=0
#SBATCH --export=ALL

#export OMP_NUM_THREADS=1

##export MV2_ENABLE_AFFINITY=0
export MV2_HOMOGENEOUS_CLUSTER=1
#module load quantum-espresso/7.1
module load quantum-espresso/7.1

mpirun -n 224   pw.x  < scf.in > scf.out

mpirun -n 224  ph.x  -pd .true. <phonon.in &> phonon.out

